version: "3.9"
services:
    backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      env_file: 
        - ./backend/.env
      restart: on-failure
      ports: 
        - 4000:4000
      depends_on:
        - postgres
      networks: 
        - database
        - default

    postgres:
      container_name: database
      image: postgres:12-alpine
      env_file: 
         - ./backend/.env
      restart: on-failure
      volumes:
        - ./pg-data:/data/postgres
      networks: 
        - database
    
    frontend:
        container_name: frontend
        build:
          context: ./frontend
          dockerfile: Dockerfile
        env_file: ./frontend/.env
        restart: on-failure
        ports: 
          - 8081:80
volumes:
  postgres:

networks:
  database: